version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - 3001:3001
    working_dir: /app-frontend
    volumes:
      - ./frontend/src:/app-frontend/src
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3001']
      timeout: 10s
      retries: 5
  backend:
    build: ./backend
    ports:
      - 3000:3000
    working_dir: /app-backend
    command: npm run dev
    volumes:
      - ./backend/src:/app-backend/src
    # depends_on:
    #   mongodb:
    #     condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongodb:27017/FitShop
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3000']
      timeout: 10s
      retries: 5
  mongodb:
    image: mongo:5.0.7
    container_name: mongodb
    platform: linux/x86_64
    ports:
      - 27017:27017
    environment:
      - MONGO_ROOT_PASSWORD=123456
    restart: 'always'
    # healthcheck:
    #   test: ['CMD', 'ping', '-h', 'localhost']
    #   timeout: 10s
    #   retries: 5
    cap_add:
      - SYS_NICE
