version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - 3001:3001
    working_dir: /frontend
    volumes:
      - ./frontend/src:/frontend/src
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3001']
      timeout: 10s
      retries: 5

  backend:
    container_name: app_backend  
    build: ./backend
    ports:
      - 3000:3000
    working_dir: /backend
    volumes:
      - ./backend/src:/backend/src
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - APP_PORT=3000
      - DB_HOST=mongodb
      - DB_USER=root
      - DB_PASS=123456
      - DB_PORT=3306
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3000']
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo:5.0.7
    container_name: radarfit_db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MONGODB_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD","ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE